TuneUp/TuneUp.csproj
TuneUp/TuneUpViewExtension.cs
TuneUp/TuneUpWindow.xaml
TuneUp/TuneUpWindow.xaml.cs
TuneUp/TuneUpWindowViewModel.cs

Now selects and focuses on the node that is selected in the TuneUp table.
@mjkkirschner @QilongTang

Focus on selected node

---

.gitignore
README.md
TuneUp.sln
TuneUp/ProfiledNodeViewModel.cs
TuneUp/Properties/AssemblyInfo.cs
TuneUp/TuneUp.csproj
TuneUp/TuneUpViewExtension.cs
TuneUp/TuneUpWindow.xaml
TuneUp/TuneUpWindow.xaml.cs
TuneUp/TuneUpWindowViewModel.cs
TuneUpTests/Properties/AssemblyInfo.cs
TuneUpTests/TuneUpTests.cs
TuneUpTests/TuneUpTests.csproj
TuneUpTests/config/TestServices.dll.config
TuneUpTests/packages.config
test/CBPointPointLine.dyn

Add profiling data state and ability to force re-execute graph

---

TuneUpTests/TuneUpTests.cs

TuneUpTests Update

---

README.md

Attach the gif which was missing due to an IO error

Attach Gif

---

README.md
TuneUp/TuneUpViewExtension.cs
TuneUpTests/TuneUpTests.cs
TuneUpTests/TuneUpTests.csproj

- Add a known issue section
- Enable checkable Menu item following workspace Refenrences as example

Enable Checkable Menu Item

---

README.md
TuneUp/TuneUpWindowViewModel.cs
TuneUp/manifests/pkg.json

Update TuneUp Package Description. I would like to add the known issues to package description so that people know what to expect without hitting our github repo.
~~Notice the package publishing is still pending.~~

Update Package Description

---

TuneUp/TuneUpViewExtension.cs

This prevents leaving Dynamo running as a zombie process after closing.

Set DynamoView as Owner of TuneUp window

---

TuneUp/TuneUp.csproj
TuneUp/manifests/pkg.json

Updated version number and description in `pkg.json`.
Small change to `csproj` file to publish on `Release` build.

Post-release v1.0.6 changes

---

TuneUp/manifests/pkg.json

Bump the tuneup version to 1.0.10.
@QilongTang @ivaylo-matov

Bump up to 1.0.10 version.

---

TuneUp/manifests/pkg.json

Update package version after https://github.com/DynamoDS/TuneUp/pull/55

Update TuneUp version specified in pkg.json

---

TuneUp/TuneUpWindowViewModel.cs
TuneUp/manifests/pkg.json

PR to address https://jira.autodesk.com/browse/DYN-7453
Modified to force Manual mode when new workspace is opened.
@QilongTang
@reddyashish
@Amoursol
@dnenov

[DYN-7453] Open New workspace and Open file options are disabled if Show TuneUp is checked

---

pipeline.yml

Use `Release` folder path instead of `Debug`

DYN-7389 Update build path

---

TuneUp/Properties/AssemblyInfo.cs
TuneUp/manifests/pkg.json

Update description and bump version.
@achintyabhat @QilongTang

Update description and bump version

---

TuneUp/manifests/pkg.json

Bump version to 1.0.14
@zeusongit @QilongTang

Bump version to 1.0.14

---

TuneUp/TuneUpWindowViewModel.cs

This PR aims to address [DYN-7577](https://jira.autodesk.com/browse/DYN-7577).
Now, groups that only contain notes (and no nodes) won’t show up in TuneUp in these situations:
- When opening a new graph that has "empty" groups
- When enabling TuneUp on a graph with "empty" groups
- When all nodes are removed from a group, leaving only notes behind
I've also added methods to create profiled groups to simplify the code and reduce some repetition.
@reddyashish 
@QilongTang 
@dnenov

[DYN-7577] Removed groups with only notes inside

---

TuneUp/Properties/AssemblyInfo.cs
TuneUp/manifests/pkg.json

Updating the assembly info version and making it 1.0.16 with the recent changes.

Update assembly info version and bump to 1.0.16

---

pipeline.yml

DYN-8349: Dynamo to Azure.

---

TuneUp/Properties/Resources.cs-CZ.resx
TuneUp/Properties/Resources.de-DE.resx
TuneUp/Properties/Resources.es-ES.resx
TuneUp/Properties/Resources.fr-FR.resx
TuneUp/Properties/Resources.it-IT.resx
TuneUp/Properties/Resources.ja-JP.resx
TuneUp/Properties/Resources.ko-KR.resx
TuneUp/Properties/Resources.pl-PL.resx
TuneUp/Properties/Resources.pt-BR.resx
TuneUp/Properties/Resources.ru-RU.resx
TuneUp/Properties/Resources.zh-CN.resx
TuneUp/Properties/Resources.zh-TW.resx

Hi , could you please review and merge this PR?
================== Word Count Statistics begin ==================
GMT Fri Mar 14 14:54:32 2025: Localization Engineer Lead for this PR is lilian.rossi@autodesk.com,MOR-REVIT-SLEs@moravia.com.
Vendor Engineer for this PR is MOR-REVIT-SLEs@moravia.com.
Localization branch is updated. 
New/Updated strings status
CHS: all strings are translated
CHT: all strings are translated
CSY: all strings are translated
DEU: all strings are translated
ESP: all strings are translated
FRA: all strings are translated
ITA: all strings are translated
JPN: all strings are translated
KOR: all strings are translated
PLK: all strings are translated
PTB: all strings are translated
RUS: all strings are translated
Please note that If the word count above shows some …

 Merge master-localization into master

---

TuneUp/TuneUpWindow.xaml
pipeline.yml

- Setup CI/CD
- Fixes some UI width adjustments

DYN-8511: Fix multiple UI issues with overflown localized elements

---

TuneUp/TuneUp.csproj
TuneUpTests/TuneUpTests.csproj
pipeline.yml

Update build to include package generation with localized content

---

.adsk/ContinuousLocalization.yml

Continuous Localization pipeline settings update.

Add en-GB language support for CL

---

TuneUp/Properties/AssemblyInfo.cs
TuneUp/manifests/pkg.json
pipeline.yml

Updated AssemblyInfo.cs, pkg.json, and pipeline.yml to version 2.0.5. Also corrected pipeline deployment to sign the en-GB resource DLL instead of a duplicate en-US entry.

Bump version to 2.0.5 and update pipeline resources
