DynamoDS/TuneUp

- TuneUp/ProfiledNodeViewModel.cs
- TuneUp/TuneUpWindow.xaml
- TuneUp/TuneUpWindow.xaml.cs
- TuneUp/TuneUpWindowViewModel.cs
This PR updates how grouping and sorting is handled for ProfiledNodesCollection. Previously, groups (such as `ExecutedOnCurrentRun` or `NotExecuted`) we're displayed in no particular order in the TuneUp window. Now they will maintain the order defined in the [ProfiledNodeState enum](https://github.com/DynamoDS/TuneUp/blob/master/TuneUp/TuneUpWindowViewModel.cs#L18-L23), with `ExecutedOnCurrentRun` (most relevant data) at the top after each graph execution.
FYI @mjkkirschner @QilongTang
> Maintain order of Profiling Data state-groups

- TuneUp/TuneUp.csproj
- TuneUp/TuneUpWindowViewModel.cs
When Nora Li from Civil Team and I were setting up Tuneup for Civil Team to consume, we were getting constant crashes which all point to null object references when launching Dynamo with TuneUp. After some debugging, I found there are multiple places which could cause such crash. Here are the fixes worked on my local system and a screen shot from Nora.
> Null Reference Crashes

- .github/workflows/msbuild.yml
- README.md
- TuneUp/ProfiledNodeViewModel.cs
- TuneUp/TuneUpWindowViewModel.cs
1. Fix all the Tuneup instances in readme and code
2. Fix a bug that user may see multiple total execution time row in certain cases. e.g. when evaluation started event did not get triggered
> Fix a Total Execution Time bug

- TuneUp/manifests/pkg.json
Opening the PR before publishing, just in case.
Took the description from published version 1.0.5 and added the `Read more here` part.
Also, I guess we need to publish a new version, so it's 1.0.7, right?
> Fix description and update to 1.0.7

- TuneUp/TuneUp.csproj
- TuneUp/TuneUpViewExtension.cs
- TuneUpTests/TuneUpTests.csproj
When TuneUp package is installed, "Show TuneUp" menu item should be present under the Extensions menu.
To use the AddExtensionMenuItem API from ViewLoadedParams class, the DynamoCore references are pointed to the Dynamo 2.12 version. The TargetFrameworkVersion is also set to v4.8.
> TuneUp menu item should be under Extensions menu.

- Directory.Build.props
- README.md
- TuneUp/TuneUp.csproj
- TuneUp/TuneUpViewExtension.cs
- TuneUpTests/TuneUpTests.cs
- TuneUpTests/TuneUpTests.csproj
As per this tread: https://autodesk.slack.com/archives/CPJ5UQW0Z/p1718630160699509
- `DynamoVisualProgramming` packages are updated to the latest version
- `NUnit` is replaced with `NUnit3` (+ NUnit3TestAdapter)
- Disabled default inclusion of all `*.cs` files to avoid duplicate compile item errors
- Disabled generation of `AssemblyInfo.cs` to avoid duplicate attributes
- Disabled default inclusion of all `*.xaml` files to avoid duplicate page item errors
- Depreciated `RequiresSTA` is replaced with `Apartment(ApartmentState.STA)` in unit tests
> Update to .NET

- TuneUp/TuneUpWindow.xaml
- TuneUp/TuneUpWindow.xaml.cs
PR aims to address https://jira.autodesk.com/browse/DYN-3033
`isUserInitiatedSelection` to flag if the nodes in DataGrid are selected by the user. This prevents `NodeAnalysisTable_SelectionChanged` focusing on selected nodes when TuneUp loads or CurrentWorkspace changes.
FYI
@QilongTang
@reddyashish
@Amoursol
> [DYN-3033] TuneUp shouldn't change the graph view when opened

- TuneUp/TuneUpWindow.xaml
- TuneUp/TuneUpWindow.xaml.cs
- TuneUp/TuneUpWindowViewModel.cs
PR aims to address https://jira.autodesk.com/browse/DYN-2369 🤞
- exports csv files with the data from `NodeAnalysisTable` (assuming this is the most appropriate format for the majority of Dynamo users) 
- new button in the UI for export
- Force Re-run button renamed to Run All as per TuneUp's ReadMe.md
FYI
@QilongTang
@reddyashish
@Amoursol
> [DYN-2369] Export TuneUp node timings

- TuneUp/TuneUpWindow.xaml
- TuneUp/TuneUpWindow.xaml.cs
- TuneUp/TuneUpWindowViewModel.cs
PR aiming to address https://jira.autodesk.com/browse/DYN-2475 🤞
- arrows appear when user changes the default sorting order / direction
- sorting order and direction are now kept on the next graph execution and revert back to default when TuneUp is closed
FYI
@QilongTang
@reddyashish
@Amoursol
> [DYN-2475] Icons for sorting on datagrid headers

- TuneUp/ProfiledNodeViewModel.cs
- TuneUp/TuneUpWindow.xaml
- TuneUp/TuneUpWindow.xaml.cs
- TuneUp/TuneUpWindowViewModel.cs
**_Aims_** to address https://jira.autodesk.com/browse/DYN-2654 🤞
Displays Groups in TuneUp:
- Each grouped node is indented and positioned under the group header, regardless of the sorting order.
- Sorting can be based on total group execution time, group execution order, or group name.
- When sorting by execution order, if a group is removed, the execution order of the previously grouped nodes will not display, but the nodes will remain in the same location.
- When nodes are grouped, TuneUp will display the group and place the nodes under the header.
- The group will initially have its default name. If the name is changed, TuneUp will update it on the next graph run.
- If the color is changed, TuneUp will update it the next time the graph is loaded.
Hope that's okay.
> [DYN-2654] groups of nodes in graph should be displayed as group in tuneup list view

- TuneUp/manifests/pkg.json
> Bump up the version to 1.0.9

- TuneUp/ProfiledNodeViewModel.cs
- TuneUp/TuneUpWindowViewModel.cs
Small PR to fix a bug in master where in some situations when `ShowGroups` is off by default the group indicator will not show.
@QilongTang
> [DYN-7334] Big fix

- TuneUp/TuneUpViewExtension.cs
- TuneUp/TuneUpWindow.xaml
- TuneUp/TuneUpWindow.xaml.cs
This PR aims to address some of the resent feedback on TuneUp's revised control layout.  It covers all points from column "3.3" of [Mural](https://app.mural.co/t/autodesk2145/m/autodesk2145/1726671147065/f22bbd9296463ee3376ffd3c5be0a9e68028b323?sender=u63a4c10277115ad8dc555082)  with the exception of point 3.
1.  Hepl icon removed
2.  Centers on node when selected in the TuneUp's UI
3.  
4.  Show TuneUp is present in the Extensions menu even when language is not English
5.  UI changes to match the intended design
6. Group title foreground color auto-adjusts for contrast with the background similarly to the groups in the workspace
7. Jagged edges removed from group nodes
@QilongTang 
@reddyashish 
@Amoursol 
@dnenov
> [DYN-7334] Improvements following the feedback

- TuneUp/TuneUpWindow.xaml
- TuneUp/TuneUpWindow.xaml.cs
PR aims to address https://jira.autodesk.com/browse/DYN-7463
The code has been modified to capture the `MouseWheel` event from the `DataGrids` and forward it to the parent `ScrollViewer`
@QilongTang
@reddyashish
@Amoursol
@dnenov
> [DYN-7463] Mouse scroll doesn't work in the TuneUp list

- TuneUp/ProfiledNodeViewModel.cs
- TuneUp/TuneUpWindow.xaml.cs
- TuneUp/TuneUpWindowViewModel.cs
- TuneUpTests/TuneUpTests.cs
PR aims to address https://jira.autodesk.com/browse/DYN-7466 .
- Group nodes are now centered when selected from the node list.
- Selecting a node from one list will deselect all selected nodes from other lists.
- ProfiledNodeViewModel now includes a GroupModel property, and IsGroup and IsGroupExecutionTime are now getter-only properties. Due to these changes, some optimizations can be made in TuneUpWindowViewModel, but they will be addressed in a future PR.
Goes along with https://github.com/DynamoDS/Dynamo/pull/15504
@QilongTang 
@reddyashish 
@Amoursol 
@dnenov
> [DYN-7466] Navigate-to-corresponding-node/group-by-clicking-it-in-the-TuneUp-list

- Jenkinsfile
- pipeline.yml
Add pipeline yaml for internal jenkins to sign and zip TuneUp
> Add pipeline yaml

- TuneUp/TuneUpWindow.xaml
- TuneUp/TuneUpWindow.xaml.cs
PR in response to https://autodesk.slack.com/archives/CPJ5UQW0Z/p1727362943286009?thread_ts=1727192978.398829&cid=CPJ5UQW0Z
I could not replicate this behavior, but forcing the ScrollViewer to focus on loading should resolve this...
Please let me know if it works.
@QilongTang 
@reddyashish
> [DYN-7463] related : force ScrollViewer to focus on loaded

- Directory.Build.props
- TuneUpTests/TuneUpTests.csproj
A follow up PR of https://github.com/DynamoDS/Dynamo/pull/15516 to depend on the newer version of Nugets so that a local hard dependency can be removed to unblock CI.
> DYN-7337 Update Nuget Reference to remove a local dependency

- TuneUp/ProfiledNodeViewModel.cs
- TuneUp/TuneUpWindowViewModel.cs
Small PR to address one of the points for improvement in [this Mural board](https://app.mural.co/t/autodesk2145/m/autodesk2145/1726671147065/f22bbd9296463ee3376ffd3c5be0a9e68028b323?sender=u63a4c10277115ad8dc555082) (don't think there is a JIRA ticket for this) :
> "3. Displaying executed nodes with 0 ms as 1 ms, as discussed in Slack."
In `OnNodeExecutionEnd`, the `TimeSpan` value is now rounded and directly assigned to `ExecutionMilliseconds` as an integer. Total group execution times are calculated as the sum of these integer values rather than exact `TimeSpan` values. Consequently, the `GroupExecutionTime` and `ExecutionTime` properties are now obsolete and removed.
> 3.4 Improvement - show executed 0ms nodes as 1ms

- TuneUp/TuneUpWindowViewModel.cs
Aims to address https://jira.autodesk.com/browse/DYN-7436
The code now check if the file is in use before trying to override it. Please let me know if this is acceptable and can implement it on `Node Graph Manager`.
@QilongTang 
@reddyashish 
@Amoursol 
@dnenov
> [DYN-7436] Dynamo crashes upon exporting results if the destination file is open

- TuneUp/ProfiledNodeViewModel.cs
- TuneUp/TuneUpWindow.xaml.cs
- TuneUp/TuneUpWindowViewModel.cs
PR aims to address pint 5 (3.4 column) from [this Mural board](https://app.mural.co/t/autodesk2145/m/autodesk2145/1726671147065/f22bbd9296463ee3376ffd3c5be0a9e68028b323?sender=u63a4c10277115ad8dc555082) and [this slack thread](https://autodesk.slack.com/archives/CPJ5UQW0Z/p1726733943662399) 
TuneUp now adds a group header and displays the group's execution time in each DataGrid containing its nodes.
@QilongTang 
@reddyashish 
@dnenov
@Amoursol
> TuneUp improvement - handling groups with nodes from different states

- TuneUp/ProfiledNodeViewModel.cs
- TuneUp/TuneUpWindowViewModel.cs
Small PR to address a couple of issues I've just noticed:
1. When a group is renamed, TuneUp doesn't show the "Group: " prefix in the nodes table.
1. When all nodes or groups are deleted from a table, the table header and footer still remain visible.
_**Before:**_
**_After:_**
@QilongTang 
@reddyashish 
@dnenov
> Bug fixes - group naming & table visibility

- TuneUp/Properties/Resources.en-US.Designer.cs
- TuneUp/Properties/Resources.en-US.resx
- TuneUp/Properties/Resources.resx
- TuneUp/TuneUp.csproj
- pipeline.yml
PR aims to address:
- pipeline.yml script isn't generating TuneUp.zip with TuneUp.dll and en-US resources. I tested this locally in PowerShell using:
`Compress-Archive -Path "TuneUp\bin\Release\net8.0-windows\TuneUp.dll", "TuneUp\bin\Release\net8.0-windows\en-US" -DestinationPath "TuneUp.zip"` which created TuneUp.zip, therefore this command:
`Compress-Archive -Path 'TuneUp/bin/Release/net8.0-windows/TuneUp.dll', 'TuneUp/bin/Release/net8.0-windows/en-US' -DestinationPath 'TuneUp.zip'` should also work in the pipeline.
- The `Resources.en-US.Designer.cs` file was not generating as expected. Renaming `Resources.en-US.resx`, running the custom tool, and renaming it back resolved the issue.
- Fixed a typo in the resources file.
@QilongTang 
@reddyashish 
@dnenov
> New paths for pipeline.yml

- TuneUp/TuneUpWindowViewModel.cs
PR aims to address [DYN-7698](https://jira.autodesk.com/browse/DYN-7698) where TuneUp does not zoom-to-fit on groups after that graph has been executed.
*This branch is built from `DYN-7697-Crash-with-Periodic-Run` as I couldn't build `master`. Relevant changes are only in `CreateGroupNodesForCollection`.
@QilongTang 
@reddyashish 
@dnenov
> [DYN-7698] Zoom to group, doesn't work

- TuneUp/manifests/pkg.json
Add more details to reduce gap between the active version maintained on PM and this repo
> Update manifest file

- TuneUp/TuneUpWindow.xaml
Small PR to address [DYN-7699](https://jira.autodesk.com/browse/DYN-7699)
@reddyashish 
@QilongTang 
@dnenov
> [DYN-7699] Panel should show run all button when panel size is very small

- TuneUp/TuneUpWindowViewModel.cs
PR to address [DYN-7701](https://jira.autodesk.com/browse/DYN-7701)
In some cases, running "Run All" was causing Dynamo to freeze up with no error messages. After looking into it, it seems the issue was due to long-running updates blocking the UI thread. I've used `Task.Run` and `uiContext.Post` to handle these updates in the background, which seems to keep things running smoothly.
For consistency and to streamline the code, I also replaced `collection.Dispatcher` calls with `uiContext.Post`, as `Dispatcher` was causing some problems in Civil 3D anyway. I've also separated the UI update code from the main methods to clean-up the logic.
> [DYN-7701] Dynamo freeze on Run All in some cases

- TuneUp/TuneUpWindowViewModel.cs
This PR aims to address [DYN-7568](https://jira.autodesk.com/browse/DYN-7568). Please see the ticket for full description of the issue.
The cause of the Revit & Dynamo crash was `ResetEngine()` in `ResetProfiling()` trying to start a transaction outside Revit's API. I removed `ResetEngine()` and worked around this by looping through the nodes in the workspace and marking them as modified manually. This should achieve the same result.
There might be some edge cases if we work with dynamic components, but it’s been stable in my tests so far.
@QilongTang 
@reddyashish 
@dnenov
> [DYN-7568] Tune-up crashes Dynamo when running all nodes in script with a selected family

- TuneUp/TuneUpWindowViewModel.cs
PR aims to address [DYN-7763](https://jira.autodesk.com/browse/DYN-7763).
The TuneUp UI previously flickered on medium-complexity graphs due to frequent updates while nodes were being moved between collections. Now, TuneUp uses temporary collections to process the nods during graph execution and the UI only updates after all nodes have executed and graph timings have been calculated.
@QilongTang 
@reddyashish 
@dnenov
> [DYN-7763] Flickering list when pressing Run All

- TuneUp/Properties/AssemblyInfo.cs
- TuneUp/manifests/pkg.json
Bump up version to reflect binary change, this is required so we can potentially make TuneUp constantly updated in Dynamo master branch
> Bump up version to reflect binary change

- README.md
- pipeline.yml
We can't use the release PR option when making releases on mirrored repositories.
I have created a follow-up improvement that would allow CILibrary to create a PR against the public repository instead (DYN-8724). But until that is done, our release process will be:
* Create a release branch on the internal repository
* Build the branch to publish
* Manually create a PR on the public repository with the changes introduced by the release branch (the only thing changed is the version number in the pipeline file).
* Review and merge this PR
* Delete the release branch on the internal repository
@AlexisErazoGlobant
> Remove the release PR option

- .github/workflows/build.yml
- TuneUp/TuneUp.csproj
> Add new locale to final build output
